resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/0c5b0a6619fadf22f4d62a12154e181a6d035c1c/snapshot.yaml

packages:
  - io-sim
  - io-sim-classes
  - network-mux
  - ntp-client
  - ouroboros-consensus
  - ouroboros-consensus-byron
  # - ouroboros-consensus-byron-test
  # - ouroboros-consensus-byronspec
  - ouroboros-consensus-cardano
  - ouroboros-consensus-mock
  - ouroboros-consensus-shelley
  # - ouroboros-consensus-test
  - ouroboros-network
  - ouroboros-network-framework
  - ouroboros-network-testing
  - typed-protocols
  - typed-protocols-examples
  - Win32-network

flags:
  io-sim-classes:
    asserts: true
  network-mux:
    asserts: true
  ouroboros-network:
    asserts: true
    cddl: true
  ouroboros-consensus:
    asserts: true
  ouroboros-consensus-byron:
    asserts: true
  ouroboros-consensus-cardano:
    asserts: true

extra-deps:
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 743f266cfe5fff11d18602faf510f22a544ea295
    subdirs:
      - contra-tracer

  - git: https://github.com/input-output-hk/cardano-base
    commit: 13f44ad35d2762dbf98b3d3be56b7ba2adf515f4
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class
      - cardano-crypto-praos
      - slotting

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: 4edcdab87510b2657c62bcf14035817ce6e23455
    subdirs:
      - byron/chain/executable-spec
      - byron/ledger/executable-spec
      - byron/ledger/impl
      - byron/ledger/impl/test
      - byron/crypto
      - byron/crypto/test
      - semantics/executable-spec
      - semantics/small-steps-test
      - shelley/chain-and-ledger/dependencies/non-integer
      - shelley/chain-and-ledger/executable-spec
      - shelley/chain-and-ledger/shelley-spec-ledger-test

  # Needed for `cardano-ledger-specs`
  - git: https://github.com/input-output-hk/goblins
    commit: cde90a2b27f79187ca8310b6549331e59595e7ba

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 0c5b0a6619fadf22f4d62a12154e181a6d035c1c
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-crypto
    commit: 2547ad1e80aeabca2899951601079408becbc92c

  - bimap-0.4.0
  - binary-0.8.7.0
  - generic-monoid-0.1.0.0
  - hedgehog-quickcheck-0.1.1
  - network-3.1.1.1
  - quiet-0.2
  - sop-core-0.5.0.1
  - statistics-linreg-0.3
  - tasty-hedgehog-1.0.0.2
  - text-1.2.4.0
  - moo-1.2
  - gray-code-0.3.1
  - Unique-0.4.7.6
  - graphviz-2999.20.1.0
  - partial-order-0.2.0.0
  - primitive-0.6.4.0

  # Windows only
  - Win32-2.6.2.0

nix:
  shell-file: nix/stack-shell.nix
